"""One analysis of one image, assembled from every signal that is actually available.

WHY THIS FILE EXISTS SEPARATELY FROM forensics.py. The forensic signals are facts about a
file. A REPORT is a document shown to a person, and the dangerous step is the one where
facts become a verdict. That step belongs somewhere explicit, with its own rules, rather
than scattered through the UI.

THE TWO RULES.

1. THE DETECTOR VERDICT IS ABSENT UNTIL A DETECTOR EXISTS. FORGE-Image's heads are not
   trained. So `detector.available` is False, `verdict` is None, and the UI says so. It
   does not say "Human, 98.2% confidence" from forensic signals, because forensic signals
   cannot support that sentence. A confident verdict with nothing behind it is the exact
   failure this project keeps finding, dressed as a product.

2. FORENSIC SIGNALS ARE NEVER SUMMED INTO A PROBABILITY. Stripped EXIF plus standard
   quantisation tables does not equal "60% AI". Those two facts describe how the file was
   written and are true of most photographs on the internet. Adding them would manufacture
   confidence out of nothing and would fire hardest on exactly the innocent inputs a
   detector must never accuse: screenshots, social-platform downloads, re-saved images.

WHAT A READER GETS INSTEAD. Facts, each with its own caveat, plus a plain statement of what
cannot be concluded. That is less satisfying than a number and it is the truthful version.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass, field

from forge.image.forensics import (
    FORENSICS_VERSION,
    Finding,
    analyze,
)
from forge.image.phash import dhash, to_hex

REPORT_VERSION = "image_report_v1"

# Fields the detector section will carry once the heads are trained. Declared here so the
# UI can be written against the final shape and simply render "not available" today.
DETECTOR_FIELDS = ("verdict", "probability", "abstain_band", "heatmap_png", "backbone")


@dataclass(frozen=True)
class DetectorResult:
    """The model's answer, or an honest statement that there is not one.

    `available` False is the current state: the architecture in forge.image.model exists,
    the training index exists, and no weights have been fitted. Everything else in a report
    is real today; this is the part that is not, and it says so.
    """

    available: bool = False
    reason: str = (
        "FORGE-Image is architecturally complete but has not been trained: no image corpus "
        "has been generated yet. Producing a verdict from the forensic signals alone would "
        "be a fabricated confidence, so none is shown."
    )
    verdict: str | None = None
    probability: float | None = None
    heatmap_png: bytes | None = None
    backbone: str | None = None

    def as_dict(self) -> dict:
        out = asdict(self)
        out.pop("heatmap_png", None)
        out["heatmap"] = "available" if self.heatmap_png else None
        return out


@dataclass(frozen=True)
class Report:
    filename: str
    size_bytes: int
    phash: str
    findings: list[Finding]
    detector: DetectorResult = field(default_factory=DetectorResult)
    forensics_version: str = FORENSICS_VERSION
    report_version: str = REPORT_VERSION
    elapsed_ms: int = 0

    def by_name(self, name: str) -> Finding | None:
        return next((f for f in self.findings if f.name == name), None)

    def as_dict(self) -> dict:
        return {
            "filename": self.filename,
            "size_bytes": self.size_bytes,
            "phash": self.phash,
            "findings": [f.as_dict() for f in self.findings],
            "detector": self.detector.as_dict(),
            "forensics_version": self.forensics_version,
            "report_version": self.report_version,
            "elapsed_ms": self.elapsed_ms,
        }

    @property
    def headline(self) -> str:
        """The single sentence shown at the top. Never a verdict we cannot support."""
        if self.detector.available and self.detector.verdict:
            return self.detector.verdict
        return "No detector verdict"

    @property
    def what_this_cannot_say(self) -> list[str]:
        """Stated explicitly in the UI, because the absence of a claim is easy to miss.

        Every line here is a conclusion a reader might otherwise draw from the panels above
        it. Naming them is cheaper than letting someone leave with the wrong impression.
        """
        lines = [
            "Whether this image was generated by AI. That needs the trained detector, and "
            "it has not been trained yet.",
        ]
        exif_finding = self.by_name("exif")
        if exif_finding and exif_finding.status != "present":
            lines.append(
                "Nothing, from the missing EXIF. Screenshots, social-platform downloads "
                "and chat apps all strip metadata from ordinary photographs."
            )
        tables = self.by_name("jpeg_tables")
        if tables and isinstance(tables.value, dict) and tables.value.get("standard_tables"):
            lines.append(
                "Nothing, from the standard quantisation tables. They mean a software "
                "library wrote the file, which is equally true of a re-saved photograph."
            )
        return lines


def build_report(data: bytes, filename: str = "upload") -> Report:
    """Analyse one image end to end. Pure CPU: no GPU, no network, no model weights."""
    import time

    started = time.perf_counter()
    findings = analyze(data)
    try:
        fingerprint = to_hex(dhash(data))
    except Exception:  # noqa: BLE001 - a hash failure must not sink the whole report
        fingerprint = ""
    elapsed = int((time.perf_counter() - started) * 1000)
    return Report(
        filename=filename,
        size_bytes=len(data),
        phash=fingerprint,
        findings=findings,
        elapsed_ms=elapsed,
    )
