"""The image service must refuse what it cannot analyse and never invent what it lacks.

An upload endpoint is where a forensic tool meets untrusted input, so the tests here are
mostly about refusal: empty bodies, non-images, oversized files. The one that matters most
is `test_the_api_never_returns_a_fabricated_verdict`, which asserts the JSON a browser
receives carries no detector answer while no detector exists. The page cannot render a
confident green banner if the payload has nothing to render it from.
"""

from __future__ import annotations

import io

import pytest

pytest.importorskip("PIL")
pytest.importorskip("fastapi")
pytest.importorskip("httpx")

from fastapi.testclient import TestClient  # noqa: E402

from api.image_main import app  # noqa: E402

client = TestClient(app)


def _photo(fmt: str = "JPEG") -> bytes:
    import numpy as np
    from PIL import Image

    rng = np.random.default_rng(7)
    y, x = np.mgrid[0:180, 0:220]
    base = 130 + 50 * np.sin(x / 15.0) + 30 * np.cos(y / 8.0) + rng.normal(0, 9, (180, 220))
    stack = np.clip(np.dstack([base, base, base]), 0, 255).astype("uint8")
    buffer = io.BytesIO()
    Image.fromarray(stack, "RGB").save(buffer, format=fmt, quality=90)
    return buffer.getvalue()


def _post(data: bytes, name: str = "a.jpg"):
    return client.post("/v1/image/analyze", files={"file": (name, data, "image/jpeg")})


def test_health_states_the_detector_is_not_loaded() -> None:
    body = client.get("/health").json()
    assert body["detector_loaded"] is False
    assert body["mode"] == "forensics-only"


def test_the_page_serves() -> None:
    response = client.get("/")
    assert response.status_code == 200
    assert "FORGE" in response.text


def test_a_real_image_is_analysed() -> None:
    body = _post(_photo()).json()
    assert body["size_bytes"] > 0
    assert len(body["phash"]) == 16
    names = {f["name"] for f in body["findings"]}
    assert "jpeg_tables" in names and "exif" in names


def test_the_api_never_returns_a_fabricated_verdict() -> None:
    """THE ONE THAT MATTERS. The page cannot show a confidence the payload does not carry."""
    body = _post(_photo()).json()
    assert body["detector"]["available"] is False
    assert body["detector"]["verdict"] is None
    assert body["detector"]["probability"] is None


def test_the_response_carries_its_own_disclaimers() -> None:
    body = _post(_photo()).json()
    assert body["what_this_cannot_say"]
    assert any("generated by AI" in line for line in body["what_this_cannot_say"])


def test_a_preview_is_returned_as_a_data_uri() -> None:
    """Uploads are never written to disk; the preview travels inline or not at all."""
    body = _post(_photo()).json()
    assert body["preview"].startswith("data:image/jpeg;base64,")


def test_an_empty_upload_is_refused() -> None:
    assert _post(b"").status_code == 400


def test_a_non_image_is_refused_with_a_reason() -> None:
    response = _post(b"#!/bin/sh\necho hello\n", name="script.sh")
    assert response.status_code == 415
    assert "unsupported" in response.json()["detail"]


def test_an_oversized_upload_is_refused_before_analysis() -> None:
    from api.image_main import MAX_BYTES

    assert _post(b"\xff\xd8" + b"\x00" * (MAX_BYTES + 1)).status_code == 413


def test_a_png_is_accepted_too() -> None:
    """The accepting side of the format rule. Refusing everything would pass a refusal test."""
    response = client.post(
        "/v1/image/analyze", files={"file": ("a.png", _photo("PNG"), "image/png")}
    )
    assert response.status_code == 200
    assert response.json()["findings"][0]["value"] == "PNG"
