"""A report must never show a verdict it cannot support.

THE FAILURE THIS GUARDS AGAINST. The reference design for this page shows a large green
"Human, 98.2% confidence" at the top. That number comes from a trained detector. FORGE-Image
has no trained detector. The tempting move is to synthesise a confidence from the forensic
signals, because they are right there and a page with an empty verdict looks unfinished.

Doing that would produce a confident sentence backed by nothing, and it would be WORST on
exactly the inputs a detector must never accuse: screenshots, chat-app downloads and
re-saved photographs all have no EXIF and library quantisation tables, so a naive
combination scores them as suspicious. The whole project is organised against that false
positive.

So `detector.available` is False, `verdict` is None, and these tests assert it stays that
way until real weights exist.
"""

from __future__ import annotations

import io

import pytest

from forge.image.report import DetectorResult, Report, build_report

pytest.importorskip("PIL")
pytest.importorskip("numpy")


def _photo(fmt: str = "JPEG") -> bytes:
    import numpy as np
    from PIL import Image

    rng = np.random.default_rng(3)
    y, x = np.mgrid[0:200, 0:260]
    base = 120 + 55 * np.sin(x / 13.0) + 35 * np.cos(y / 9.0) + rng.normal(0, 10, (200, 260))
    stack = np.clip(np.dstack([base, base * 0.95, base * 1.02]), 0, 255).astype("uint8")
    buffer = io.BytesIO()
    Image.fromarray(stack, "RGB").save(buffer, format=fmt, quality=90)
    return buffer.getvalue()


def test_no_verdict_is_produced_without_a_detector() -> None:
    """The regression this file exists for."""
    report = build_report(_photo())
    assert report.detector.available is False
    assert report.detector.verdict is None
    assert report.detector.probability is None
    assert report.headline == "No detector verdict"


def test_the_absent_verdict_explains_itself() -> None:
    """An empty panel reads as broken. A stated reason reads as a decision."""
    reason = build_report(_photo()).detector.reason.lower()
    assert "has not been trained" in reason
    assert "fabricated" in reason


def test_the_report_states_what_it_cannot_conclude() -> None:
    lines = " ".join(build_report(_photo()).what_this_cannot_say).lower()
    assert "whether this image was generated by ai" in lines


def test_missing_exif_adds_an_explicit_disclaimer() -> None:
    """A reader who sees 'EXIF: not found' will draw a conclusion unless told not to."""
    lines = " ".join(build_report(_photo()).what_this_cannot_say).lower()
    assert "screenshots" in lines


def test_standard_tables_add_an_explicit_disclaimer() -> None:
    lines = " ".join(build_report(_photo()).what_this_cannot_say).lower()
    assert "software library" in lines


def test_a_report_carries_the_measurements() -> None:
    report = build_report(_photo(), filename="beach.jpg")
    assert report.filename == "beach.jpg"
    assert report.size_bytes > 0
    assert len(report.phash) == 16
    assert report.by_name("file_type").value == "JPEG"
    assert report.elapsed_ms >= 0


def test_serialisation_never_leaks_pixels() -> None:
    """A report is JSON sent to a browser and possibly logged. It carries measurements and
    a hash, never image bytes."""
    payload = build_report(_photo()).as_dict()
    for value in payload.values():
        assert not isinstance(value, (bytes, bytearray))
    assert payload["detector"]["heatmap"] is None


def test_a_trained_detector_would_surface_its_verdict() -> None:
    """The accepting side: when weights do exist, the headline must show them.

    Without this, `headline` could be hardcoded to the placeholder and nobody would notice
    on the day the model lands.
    """
    report = Report(
        filename="x.jpg",
        size_bytes=10,
        phash="0" * 16,
        findings=[],
        detector=DetectorResult(
            available=True, verdict="Likely AI-generated", probability=0.91,
            backbone="dinov3-vitb16", reason="",
        ),
    )
    assert report.headline == "Likely AI-generated"
    assert report.as_dict()["detector"]["probability"] == 0.91
